### ISSUE TITLE
Resolution is too big on a Steam Deck

### ISSUE THREAD

**Issue by lawnchairworld** [qrrk/Catapult#155] opened 2024-06-05 00:19 UTC
![image](https://github.com/qrrk/Catapult/assets/171110077/7d257250-8e65-4d47-a93d-dbbbd4794b1f)
impossible to use

**Comment by qrrk** [comment] 2024-06-07 17:19
This is a known issue with screens that are small but pixel-dense. As a workaround, set this is `catapult_settings.json`:
```
"ui_scale_override": 1,
"ui_scale_override_enabled": true,
```

**Comment by lawnchairworld** [comment] 2024-06-07 22:36
thank you

**Comment by AriaMoradi** [comment] 2024-08-16 19:05
duplicate of #98

**Closed by AriaMoradi** 2024-08-16 19:05 UTC
